import "./globals.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Yorik's Space",
  description: "Generated by yorik",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body>{children}</body>
    </html>
  );
}
