import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Yorikhu's Space",
  description: "Generated by yorikhu",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
